# https://goframe.org/docs/web/server-config-file-template
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  server-root: "resource/public"
  cas-sso: false
  accessLogEnabled: true
  logger:
    level: "info"

cas-sso:
  cas-server-url: https://sso-test.exodushk.com/cas
  service-url: http://localhost:8000
  # ServerURL: "https://sso-prod.yax.tech/cas"
  # Service: "http://localhost:8000"
  validate-url: "/serviceValidate"
  login-url: "/login"
  logout-url: "/logout"

admin:
  author_enable: true
  admin_users:
    - "tangshoubin"

# https://goframe.org/docs/core/glog-config
logger:
  level: "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:yax_ops_dt2_cicdgf:ZS9ArFJznAbObCf@tcp(yax-ops-dt2-mysql0.yax.tech:3306)/yax_ops_dt2_cicdgf"
    # debug: true

redis:
  default:
    address: yax-ops-dt2-valkey-sentinel01.yax.tech:6379
    db: 10

# Template.
viewer:
  paths: ["resource/template"]
  default-file: "index.html"
  delimiters: ["{{", "}}"]
  debug: true
