// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ui

import (
	"cicdgf/api/ui"
)

type ControllerV1 struct{}

func NewV1() ui.IUiV1 {
	return &ControllerV1{}
}
