// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ui

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type UiReq struct {
	g.Meta `path:"/" tags:"ui" method:"get" summary:"ui console index"`
}

type UserGetListReq struct {
	g.Meta `path:"/users" tags:"ui" method:"get" summary:"ui console index"`
}

type GroupGetListReq struct {
	g.Meta `path:"/groups" tags:"ui" method:"get" summary:"ui console index"`
}

type GroupGetOneReq struct {
	g.Meta `path:"/groups/{id}" tags:"ui" method:"get" summary:"ui console index"`
}

type GroupCreateReq struct {
	g.Meta `path:"/groups" tags:"ui" method:"post" summary:"ui console index"`
}

type IUiV1 interface {
	Ui(ctx context.Context, req *UiReq) (res *ghttp.Response, err error)
	User(ctx context.Context, req *UserGetListReq) (res *ghttp.Response, err error)
	GroupGetList(ctx context.Context, req *GroupGetListReq) (res *ghttp.Response, err error)
	GroupGetOne(ctx context.Context, req *GroupGetOneReq) (res *ghttp.Response, err error)
	GroupCreate(ctx context.Context, req *GroupCreateReq) (res *ghttp.Response, err error)
}

type ControllerV1 struct{}

func NewV1() IUiV1 {
	return &ControllerV1{}
}
